### ISSUE TITLE
docker-compose fails

### ISSUE THREAD

**Issue by k0nsl** [paragonie/airship#171]
- [ ] Check this box if this is a security vulnerability.

### Summary

`docker-compose up` on my Debian Jessie box fails.

### Expected Outcome

Successfully fire up `airship`.

### What Actually Happened

It failed.

### Relevant Debug Information

I run `docker-compose up` and it fails here:
```
Removing intermediate container d621f4c4272e
Step 4 : RUN apt-get -y install wget git composer postgresql php7.2 php7.1-cli                        php7.1-fpm php7.1-json php7.1-pgsql php7.1-curl                        php7.1-xml php7.1-dev php7.1-zip php7.1-mbstring                        composer apache2 php-pear libapache2-mod-php7.1                        php7.1-gd
 ---> Running in 7db0a4a3c197
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php7.2
E: Couldn't find any package by glob 'php7.2'
E: Couldn't find any package by regex 'php7.2'
E: Unable to locate package php7.1-cli
E: Couldn't find any package by glob 'php7.1-cli'
E: Couldn't find any package by regex 'php7.1-cli'
E: Unable to locate package php7.1-fpm
E: Couldn't find any package by glob 'php7.1-fpm'
E: Couldn't find any package by regex 'php7.1-fpm'
E: Unable to locate package php7.1-json
E: Couldn't find any package by glob 'php7.1-json'
E: Couldn't find any package by regex 'php7.1-json'
E: Unable to locate package php7.1-pgsql
E: Couldn't find any package by glob 'php7.1-pgsql'
E: Couldn't find any package by regex 'php7.1-pgsql'
E: Unable to locate package php7.1-curl
E: Couldn't find any package by glob 'php7.1-curl'
E: Couldn't find any package by regex 'php7.1-curl'
E: Unable to locate package php7.1-xml
E: Couldn't find any package by glob 'php7.1-xml'
E: Couldn't find any package by regex 'php7.1-xml'
E: Unable to locate package php7.1-dev
E: Couldn't find any package by glob 'php7.1-dev'
E: Couldn't find any package by regex 'php7.1-dev'
E: Unable to locate package php7.1-zip
E: Couldn't find any package by glob 'php7.1-zip'
E: Couldn't find any package by regex 'php7.1-zip'
E: Unable to locate package php7.1-mbstring
E: Couldn't find any package by glob 'php7.1-mbstring'
E: Couldn't find any package by regex 'php7.1-mbstring'
E: Unable to locate package libapache2-mod-php7.1
E: Couldn't find any package by glob 'libapache2-mod-php7.1'
E: Couldn't find any package by regex 'libapache2-mod-php7.1'
E: Unable to locate package php7.1-gd
E: Couldn't find any package by glob 'php7.1-gd'
E: Couldn't find any package by regex 'php7.1-gd'
ERROR: Service 'airship' failed to build: The command '/bin/sh -c apt-get -y install wget git composer postgresql php7.2 php7.1-cli                        php7.1-fpm php7.1-json php7.1-pgsql php7.1-curl                        php7.1-xml php7.1-dev php7.1-zip php7.1-mbstring                        composer apache2 php-pear libapache2-mod-php7.1                        php7.1-gd' returned a non-zero code: 100
root@ragnarok:~/airship#
```
Any ideas what went wrong?

**Comment by kelunik** [comment]
It's a simple typo in https://github.com/paragonie/airship/commit/92e74630fee822079f31e6b9200f062f43b5481c, should be `php-7.1` instead of `php-7.2`.

**Comment by ofrzeta** [comment]
Still won't work because there is no PHP 7.1 in Ubuntu 16.04 or 16.10.

**Comment by paragonie-scott** [comment]
That's ok, we're going to be releasing Airship v2.0.0 for PHP 7.2.0 when it's available, which requires adding ondrej's PPA anyway.

For now, stick to the v1.x branch if you need anything production-ready.

**Comment by ofrzeta** [comment]
I get that. But most people will just clone master (because the docs say "There's a docker-compose.yml file in the main repo ..") and then docker build will fail.  Maybe link to the v1.x branch? I am currently working on patch for Dockerfile on master to make it work (for me) with Ubuntu 16.10 and PHP 7.1. In case you are interested I can send a PR.

**Comment by paragonie-scott** [comment]
Sure. That's be greatly appreciated. :)

> Maybe link to the v1.x branch?

Sorry to say, but I don't know the first thing about Docker or how most people use it. Is this as simple as updating the README or is there some other magic that needs to be done (e.g. like with composer.json and Packagist)?

**Comment by ofrzeta** [comment]
Sorry, I did not make myself clear. By "linking to" I meant a http link from the Airship docs to the v1.x branch instead of master (first link on this page: https://github.com/paragonie/airship-docs/blob/master/en-us/01-intro/2-Installing.md). So people will checkout the right branch. 

I will send a PR for the Dockerfile on master.

**Comment by paragonie-scott** [comment]
Should this be fixable by now, since PHP 7.2 is available?

**Comment by JoshHarmon** [comment]
@paragonie-scott I've been playing around tonight with an Ubuntu 17.10 (rationale: 16.10 is unsupported)/PHP 7.2 version of the Dockerfile with all the sodium download and PECL stuff removed (as well as php-dev because we shouldn't need to build anything against php anymore now that sodium is core), along with redundant enables of mod_rewrite and two references to installing composer in the initial apt-get install :).

I also made a tweak to make apache not quit. Apparently `-D FOREGROUND` and `-DFOREGROUND` don't get treated the same, based on my rudimentary googling and testing.

It's probably stable enough for me to PR if you're interested. The docker-compose works on my system (famous last words, I know) without any issues, and it's significantly faster with all the BS removed.

**Comment by JoshHarmon** [comment]
@paragonie-scott this can be closed AFAICT

**Comment by paragonie-scott** [comment]
Excellent :)
