### ISSUE TITLE
"Undefined index: email" when trying to launch airship

### ISSUE THREAD

**Issue by alfalfascout** [paragonie/airship#196]
- [ ] Check this box if this is a security vulnerability.

### Summary

I got through the composer portion of the installation. Now I'm on the configuration portion in browser. It makes no difference whether I configure things automatically or not, it always exits with an error related to email. Do I need email for an airship? Why don't the installation instructions mention it? Or did I miss it somehow?

### Expected Outcome

My blog will be set up and running when I click the "Launch Your Airship" button

### What Actually Happened

`tail` of my web server's error log: 
```2017/12/14 01:34:16 [error] 29317#29317: *216 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: email in /xxx/xxx/airship/src/Installer/Install.php on line 676" while reading response header from upstream```

**Comment by JoshHarmon** [comment]
I believe you, since I see some reference to an email config option on L676 of Install.php (and haven't found a field in the Twig templates that would set that option), but I haven't been able to reproduce this error for myself. Are you running with docker-compose or with a manual install? I'm wonder if there could be a difference in the PHP configs we're working with that may hide the error in the containers, as I'm not seeing any output.

**Comment by alfalfascout** [comment]
If it's relevant at all, I compiled php 7.2 from source with the configure command:
```./configure --with-zlib --with-openssl --enable-fpm --with-mysqli --with-pgsql --with-pdo-pgsql```

Did I miss anything? Do I need to install any php extensions that I might be missing?

**Comment by paragonie-scott** [comment]
Somehow, this data (which should be defined) isn't defined. So I'll make it default to some non-empty value.

https://github.com/paragonie/airship/commit/5baa6459cfaf9d24724b8118d03a244f465ddcbe
